networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24

services:
  validator0:
    container_name: validator0
    image: allorad
    environment:
      - HOME=/data/validator0
    volumes:
      - /Volumes/Data/01_Projects/blockchains/1/06_upShot/01_Source/allora/allora-chain/test/devnet:/data
    user: "501:20"
    entrypoint:
      - allorad
    command:
      - --home=/data/validator0
      - start
      - --moniker=validator0
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=af35450b584603d422d42ad4e1bc77e618710f35@192.168.250.10:26656,11813576cfb62c104f70cdb5fdaead712c4f87e2@192.168.250.11:26656,77ac6074ef5d5d69ced17b6d8fff22b04bcbc44f@192.168.250.12:26656
      - --log_level debug
    ports:
      - 26657:26657
    networks:
      local-net:
        aliases:
          - validator0
        ipv4_address: 192.168.250.10
  validator1:
    container_name: validator1
    image: allorad
    environment:
      - HOME=/data/validator1
    volumes:
      - /Volumes/Data/01_Projects/blockchains/1/06_upShot/01_Source/allora/allora-chain/test/devnet:/data
    user: "501:20"
    entrypoint:
      - allorad
    command:
      - --home=/data/validator1
      - start
      - --moniker=validator1
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=af35450b584603d422d42ad4e1bc77e618710f35@192.168.250.10:26656,11813576cfb62c104f70cdb5fdaead712c4f87e2@192.168.250.11:26656,77ac6074ef5d5d69ced17b6d8fff22b04bcbc44f@192.168.250.12:26656
      - --log_level debug
    ports:
      - 26658:26657
    networks:
      local-net:
        aliases:
          - validator1
        ipv4_address: 192.168.250.11
  validator2:
    container_name: validator2
    image: allorad
    environment:
      - HOME=/data/validator2
    volumes:
      - /Volumes/Data/01_Projects/blockchains/1/06_upShot/01_Source/allora/allora-chain/test/devnet:/data
    user: "501:20"
    entrypoint:
      - allorad
    command:
      - --home=/data/validator2
      - start
      - --moniker=validator2
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=af35450b584603d422d42ad4e1bc77e618710f35@192.168.250.10:26656,11813576cfb62c104f70cdb5fdaead712c4f87e2@192.168.250.11:26656,77ac6074ef5d5d69ced17b6d8fff22b04bcbc44f@192.168.250.12:26656
      - --log_level debug
    ports:
      - 26659:26657
    networks:
      local-net:
        aliases:
          - validator2
        ipv4_address: 192.168.250.12
