version: "3"

services:
  validator0:
    container_name: validator0
    # build: .
    image: "alloranetwork/allora-chain:latest"
    environment:
      - NETWORK=testnet
      - MONIKER=validator0
      - APP_HOME=/data
    volumes:
      - ./data:/data
      - ./scripts/:/scripts
    ports:
      - "26656-26657:26656-26657"
    user: "0:0"
    entrypoint: /scripts/l1_node.sh
