version: "3"

services:
  validator0:
    container_name: validator0
    build: .
    image: "696230526504.dkr.ecr.us-east-1.amazonaws.com/allora-chain:v0.0.3"
    environment:
      - NETWORK=edgenet
      - BLOCKLESS_API_URL=
    #   - LOG=${LOG:-simd.log}
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ./.testnets:/data
    networks:
      localnet:
        # ipv4_address: 192.168.10.2

networks:
  localnet:
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.10.0/25