services:
  validator0:
    container_name: validator0
    image: allorad
    environment:
      - HOME=/data/validator0
    volumes:
      - ./${CHAIN_ID:-devnet}:/data
    user: "${UID_GID:-0:0}"
    command:
      - --home=/data/validator0
      - start
      - --moniker=validator0
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=${PEERS}
    ports:
      - ${VALIDATOR0_PORTS:-26657:26657}
    networks:
      local-net:
        aliases:
          - validator0
        ipv4_address: ${NETWORK_PREFIX:-192.168.250}.10

  validator1:
    container_name: validator1
    image: allorad
    environment:
      - HOME=/data/validator1
    volumes:
      - ./${CHAIN_ID:-devnet}:/data
    user: "${UID_GID:-0:0}"
    command:
      - --home=/data/validator1
      - start
      - --moniker=validator1
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=${PEERS}
    ports:
      - ${VALIDATOR1_PORTS:-26658:26657}
    networks:
      local-net:
        aliases:
          - validator1
        ipv4_address: ${NETWORK_PREFIX:-192.168.250}.11

  validator2:
    container_name: validator2
    image: allorad
    environment:
      - HOME=/data/validator2
    volumes:
      - ./${CHAIN_ID:-devnet}:/data
    user: "${UID_GID:-0:0}"
    command:
      - --home=/data/validator2
      - start
      - --moniker=validator2
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=${PEERS}
    ports:
      - ${VALIDATOR2_PORTS:-26659:26657}
    networks:
      local-net:
        aliases:
          - validator2
        ipv4_address: ${NETWORK_PREFIX:-192.168.250}.12

networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX:-192.168.250}.0/24
