services:
  validator0:
    container_name: validator0
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
      - HOME=/data/validator0
    volumes:
      - ./testnet:/data
    # ports:
    #   - "26656-26657:26656-26657"
    user: "1000:1000"
    command:
      - --home=/data/validator0
      - start
      - --moniker=validator0
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      local-net:
        aliases:
          - validator0
        ipv4_address: 172.20.0.10

  validator1:
    container_name: validator1
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
      - HOME=/data/validator1
    volumes:
      - ./testnet:/data
    # ports:
    #   - "26656-26657:26656-26657"
    user: "1000:1000"
    command:
      - --home=/data/validator1
      - start
      - --moniker=validator1
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      local-net:
        aliases:
          - validator1
        ipv4_address: 172.20.0.11

  validator2:
    container_name: validator2
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
      - HOME=/data/validator2
    volumes:
      - ./testnet:/data
    # ports:
    #   - "26656-26657:26656-26657"
    user: "1000:1000"
    command:
      - --home=/data/validator2
      - start
      - --moniker=validator2
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      local-net:
        aliases:
          - validator2
        ipv4_address: 172.20.0.12

  head0:
    # 12D3KooWLnJ8DdELdx94UGYfDknTnQsZkfVYpTm576nj6uVB6G8w
    container_name: head0
    image: alloranetwork/allora-inference-base-head:latest
    user: "1000:1000"
    volumes:
      - ./testnet/head0:/data
    working_dir: /data
    environment:
      - HOME=/data
    entrypoint:
      # - "/bin/bash"
      # - "-c"
      # - |
      #   allora-node --role=head --peer-db=/data/peerdb --function-db=/data/function-db  \
      #     --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
      #     --private-key=/data/keys/priv.bin --log-level=debug --port=9010 --rest-api=:6000
      - allora-node
      - --role=head
      - --peer-db=/data/peer-database
      - --function-db=/data/function-database
      - --workspace=/tmp/node
      - --private-key=/data/key/priv.bin
      - --log-level=debug
      - --port=9010
      - --rest-api=:6000
      - --allora-node-rpc-address=http://172.20.0.10:26657
      - --allora-chain-home-dir=/data/.allorad
      - --allora-chain-key-name=head0
      # - --allora-chain-topic-id={{.rootValues.alloraChainTopicId}}
    # ports:
    #   - "6000:6000"
    networks:
      local-net:
        aliases:
          - head0
        ipv4_address: 172.20.0.20

  topic0:
    container_name: worker0
    image: alloranetwork/allora-inference-base:latest
    user: "1000:1000"
    volumes:
      - ./testnet/worker0:/app
      - ./inference_linear.py:/app/main.py
    working_dir: /app
    entrypoint:
      # - "/bin/bash"
      # - "-c"
      # - |
      #   allora-node --role=head --peer-db=/data/peerdb --function-db=/data/function-db  \
      #     --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
      #     --private-key=/data/keys/priv.bin --log-level=debug --port=9010 --rest-api=:6000
      - allora-node
      - --role=worker
      - --peer-db=/data/pdb
      - --function-db=/data/fdb
      - --runtime-path=/app/runtime
      - --runtime-cli=bls-runtime
      - --workspace=workspace
      - --private-key=/data/keys/priv.bin
      - --log-level=debug
      - --port=9010
      - --boot-nodes=12D3KooWLnJ8DdELdx94UGYfDknTnQsZkfVYpTm576nj6uVB6G8w@172.20.0.20:9010
      - --allora-chain-home-dir=/data/.allorad
      - --allora-node-rpc-address=http://172.20.0.10:26657
      - --allora-chain-key-name=worker0
      - --allora-chain-topic-id=1
      - --topic=1

    # ports:
    #   - "6000:6000"
    networks:
      local-net:
        aliases:
          - head0
        ipv4_address: 172.20.0.20





networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24


