services:
  validator0:
    container_name: validator0
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
    volumes:
      - ./testnet:/data
      - ./scripts/:/scripts
    # ports:
    #   - "26656-26657:26656-26657"
    user: "0:0"
    command:
      - --home=/data/validator0
      - start
      - --moniker=validator0
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      eth-model-local:
        aliases:
          - inference
        ipv4_address: 172.20.0.10

  validator1:
    container_name: validator1
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
    volumes:
      - ./testnet:/data
      - ./scripts/:/scripts
    # ports:
    #   - "26656-26657:26656-26657"
    user: "0:0"
    command:
      - --home=/data/validator1
      - start
      - --moniker=validator1
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      eth-model-local:
        aliases:
          - validator1
        ipv4_address: 172.20.0.11

  validator2:
    container_name: validator2
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
    volumes:
      - ./testnet:/data
      - ./scripts/:/scripts
    # ports:
    #   - "26656-26657:26656-26657"
    user: "0:0"
    command:
      - --home=/data/validator2
      - start
      - --moniker=validator0
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      eth-model-local:
        aliases:
          - validator2
        ipv4_address: 172.20.0.12


networks:
  eth-model-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24


