services:
  validator0:
    container_name: validator0
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
      - HOME=/data/validator0
    volumes:
      - ./testnet:/data
    # ports:
    #   - "26656-26657:26656-26657"
    user: "1000:1000"
    command:
      - --home=/data/validator0
      - start
      - --moniker=validator0
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      local-net:
        aliases:
          - inference
        ipv4_address: 172.20.0.10

  validator1:
    container_name: validator1
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
      - HOME=/data/validator1
    volumes:
      - ./testnet:/data
    # ports:
    #   - "26656-26657:26656-26657"
    user: "1000:1000"
    command:
      - --home=/data/validator1
      - start
      - --moniker=validator1
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      local-net:
        aliases:
          - validator1
        ipv4_address: 172.20.0.11

  validator2:
    container_name: validator2
    image: allorad
    # env_file:
    #   - .environment
    environment:
      - PEERS
      - HOME=/data/validator2
    volumes:
      - ./testnet:/data
    # ports:
    #   - "26656-26657:26656-26657"
    user: "1000:1000"
    command:
      - --home=/data/validator2
      - start
      - --moniker=validator2
      - --minimum-gas-prices=0uallo
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.persistent_peers=$PEERS
    networks:
      local-net:
        aliases:
          - validator2
        ipv4_address: 172.20.0.12


  # head:
  #   # 12D3KooWPaHbkXmKQLrQ8xfQj39pvbfhrQSWMqJSCAE9WYaqcE7R
  #   container_name: head-coin
  #   image: alloranetwork/allora-inference-base-head:latest
  #   environment:
  #     - HOME=/data
  #   entrypoint:
  #     - "/bin/bash"
  #     - "-c"
  #     - |
  #       if [ ! -f /data/keys/priv.bin ]; then
  #         echo "Generating new private keys..."
  #         mkdir -p /data/keys
  #         cd /data/keys
  #         allora-keys
  #       fi
  #       allora-node --role=head --peer-db=/data/peerdb --function-db=/data/function-db  \
  #         --runtime-path=/app/runtime --runtime-cli=bls-runtime --workspace=/data/workspace \
  #         --private-key=/data/keys/priv.bin --log-level=debug --port=9010 --rest-api=:6000
  #   ports:
  #     - "6000:6000"
  #   volumes:
  #     - head-data:/data
  #   working_dir: /data
  #   networks:
  #     local-net:
  #       aliases:
  #         - head
  #       ipv4_address: 172.20.0.100



networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24


